### PR TITLE
Clean button

### PR DESCRIPTION
**Pull request by m1ga**
Adding a `clean` button to the menu:
screenshot_20180318_200314

Not sure about the trash icon but didn't find any better in the octicons :)

### CODE REVIEW

**Comment by chrisbowley** [comment]
Thanks @m1ga, looks great! I prefer to put the clean command in the menu with a keyboard shortcut (e.g. Ctrl+Alt+K). What do you think? We can accept the PR and make the UI changes unless you would like to?

**Comment by m1ga** [comment]
Go ahead and add the short-cut! I wasn't sure which one is free or used in Studio :-)

**Comment by chrisbowley** [comment]
Sorry, I meant instead of adding a toolbar button, this command should be a menu item.

**Comment by m1ga** [comment]
Ah ok, I've removed the icon and added the shortcut

**Comment by chrisbowley** [comment]
Awesome, thanks!

**Comment by hansemannn** [comment]
Thanks again @m1ga, v1.2.0 has just been released!

**Comment by eliegkassouf** [comment]
Thank you for adding this! Loving the new atom package!

**Pull request merged**
