### PR TITLE
feat(toolbar): add quick clean button to toolbar (#161)

### PR DESCRIPTION
**Pull request by developer82**

### CODE REVIEW

**Comment by ewanharris** [comment]
@developer82 thanks for the PR! We'll review this in the next few days but a couple things need doing before we could merge it, 

* Could you please [sign the CLA](https://cla.axway.com/)
* I had to fix our master branch and it's introduced some conflicts/secondary commits to this PR (sorry!). I think you should be able to rebase your branch against our master to fix that, or cherry-pick your commit to a new branch created from the master branch and open a new PR

**Comment by ewanharris** [comment]
@developer82, I've cherry-picked your commit into a new branch and created a new PR. I'd love to get this into our next release put I can't merge until the CLA has been signed. Could you ping back when it has been please

**Comment by developer82** [comment]
@ewanharris done.
Can I now push more changes?

**Comment by ewanharris** [comment]
@developer82, Could I get you to open a new PR with [your changes](https://github.com/appcelerator/atom-appcelerator-titanium/pull/173/commits/c6433d0b7090984a2a48857e2103a1f0bd7a4f1f). That'll ensure that the CLA bot picks up you as the author and verifies everything correctly (it didn't do that when I cherry-picked your commit to a new branch/PR)

**Pull request closed without merging**
